/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubespbo;
import java.sql.*;
import koneksi.koneksi;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author GAMARA DIMAS MALIK
 */
public class mainview extends javax.swing.JFrame {
    int reguler, premium;
    
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;

    /**
     * Creates new form register
     */
    public mainview() {
        initComponents();
        nama_home.setText(register.name + "!");
        kosong();
        datatable();
    }
    
    protected void aktif(){
        lblnama_order.requestFocus();
    }
    
    protected void kosong(){
         lblnama_order.setText("");
         lblalamat_order.setText("");
         lblnohp_order.setText("");
         totalharga.setText("");
         kualitas.clearSelection();
         pilihproduk.getSelectedItem();
    }
    
    protected void datatable(){
        String[] Data ={"Produk", "Kualitas", "Harga"};
        tabmode = new DefaultTableModel(null, Data);
        datatable.setModel(tabmode);
        String sql = "select*from formorder";
        
        try{
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String pilihproduk = hasil.getString("Produk");
                String pilihkualitas = hasil.getString("Kualitas");
                String totalharga = hasil.getString("Total Harga");
                String[] DataOrder = {pilihproduk, pilihkualitas, totalharga};
                tabmode.addRow(DataOrder);
            }
            datatable.setModel(tabmode);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kualitas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnmyorder = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnorderproduk = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nama_home = new javax.swing.JLabel();
        btnabout = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        orderprodukpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        myorderpanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        formorderpanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btncheckout = new javax.swing.JButton();
        lblalamat_order = new javax.swing.JTextField();
        lblnama_order = new javax.swing.JTextField();
        lblnohp_order = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        totalharga = new javax.swing.JTextField();
        pilihproduk = new javax.swing.JComboBox<>();
        rdreguler = new javax.swing.JRadioButton();
        rdpremium = new javax.swing.JRadioButton();
        batal = new javax.swing.JButton();
        aboutpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PayungIN.io");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        menupanel.setBackground(new java.awt.Color(0, 153, 204));
        menupanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 102)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("PayungIN.io");

        btnmyorder.setBackground(new java.awt.Color(255, 255, 204));
        btnmyorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmyorderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmyorderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmyorderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnmyorderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnmyorderMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("My Order");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubespbo/shopping-bag-icon.png"))); // NOI18N

        javax.swing.GroupLayout btnmyorderLayout = new javax.swing.GroupLayout(btnmyorder);
        btnmyorder.setLayout(btnmyorderLayout);
        btnmyorderLayout.setHorizontalGroup(
            btnmyorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnmyorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(51, 51, 51))
        );
        btnmyorderLayout.setVerticalGroup(
            btnmyorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnmyorderLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btnmyorderLayout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnorderproduk.setBackground(new java.awt.Color(255, 255, 204));
        btnorderproduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnorderproduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnorderprodukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnorderprodukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnorderprodukMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnorderprodukMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnorderprodukMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Order Produk");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubespbo/shopping-icon.png"))); // NOI18N

        javax.swing.GroupLayout btnorderprodukLayout = new javax.swing.GroupLayout(btnorderproduk);
        btnorderproduk.setLayout(btnorderprodukLayout);
        btnorderprodukLayout.setHorizontalGroup(
            btnorderprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnorderprodukLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        btnorderprodukLayout.setVerticalGroup(
            btnorderprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnorderprodukLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btnorderprodukLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnlogout.setBackground(new java.awt.Color(255, 255, 204));
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnlogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnlogoutMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Log Out");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubespbo/Sign-StandBy-icon.png"))); // NOI18N

        javax.swing.GroupLayout btnlogoutLayout = new javax.swing.GroupLayout(btnlogout);
        btnlogout.setLayout(btnlogoutLayout);
        btnlogoutLayout.setHorizontalGroup(
            btnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnlogoutLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        btnlogoutLayout.setVerticalGroup(
            btnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnlogoutLayout.createSequentialGroup()
                .addGroup(btnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnlogoutLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel24))
                    .addGroup(btnlogoutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(24, 24, 24))
        );

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Selamat Datang");

        nama_home.setForeground(new java.awt.Color(255, 255, 255));

        btnabout.setBackground(new java.awt.Color(255, 255, 204));
        btnabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnaboutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnaboutMouseReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("About");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubespbo/Sign-Alert-icon.png"))); // NOI18N

        javax.swing.GroupLayout btnaboutLayout = new javax.swing.GroupLayout(btnabout);
        btnabout.setLayout(btnaboutLayout);
        btnaboutLayout.setHorizontalGroup(
            btnaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnaboutLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnaboutLayout.setVerticalGroup(
            btnaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnaboutLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btnaboutLayout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubespbo/Umbrella-icon (1).png"))); // NOI18N

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnmyorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnabout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnorderproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(nama_home, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama_home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(36, 36, 36)
                .addComponent(btnorderproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnmyorder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnabout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        mainpanel.setBackground(new java.awt.Color(0, 153, 153));
        mainpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 51)));
        mainpanel.setLayout(new java.awt.CardLayout());

        orderprodukpanel.setBackground(new java.awt.Color(0, 153, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("Price List");

        jButton1.setText("Order Sekarang");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orderprodukpanelLayout = new javax.swing.GroupLayout(orderprodukpanel);
        orderprodukpanel.setLayout(orderprodukpanelLayout);
        orderprodukpanelLayout.setHorizontalGroup(
            orderprodukpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderprodukpanelLayout.createSequentialGroup()
                .addGroup(orderprodukpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderprodukpanelLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel6))
                    .addGroup(orderprodukpanelLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButton1)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        orderprodukpanelLayout.setVerticalGroup(
            orderprodukpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderprodukpanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(155, 155, 155))
        );

        mainpanel.add(orderprodukpanel, "card2");

        myorderpanel.setBackground(new java.awt.Color(0, 153, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText("My Order");

        datatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(datatable);

        javax.swing.GroupLayout myorderpanelLayout = new javax.swing.GroupLayout(myorderpanel);
        myorderpanel.setLayout(myorderpanelLayout);
        myorderpanelLayout.setHorizontalGroup(
            myorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myorderpanelLayout.createSequentialGroup()
                .addGroup(myorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myorderpanelLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel7))
                    .addGroup(myorderpanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        myorderpanelLayout.setVerticalGroup(
            myorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myorderpanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        mainpanel.add(myorderpanel, "card3");

        formorderpanel.setBackground(new java.awt.Color(0, 153, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 102));
        jLabel10.setText("ORDER FORM");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 102));
        jLabel11.setText("No. Handphone");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 102));
        jLabel12.setText("Nama");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 102));
        jLabel13.setText("Pilih Produk");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 102));
        jLabel14.setText("Alamat");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 102));
        jLabel15.setText("Pilih Kualitas");

        btncheckout.setText("Checkout");
        btncheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncheckoutMouseClicked(evt);
            }
        });
        btncheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckoutActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 102));
        jLabel16.setText("Total Harga");

        totalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalhargaActionPerformed(evt);
            }
        });

        pilihproduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Produk", "Payung", "Jas Hujan" }));
        pilihproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihprodukActionPerformed(evt);
            }
        });

        kualitas.add(rdreguler);
        rdreguler.setText("Reguler");
        rdreguler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdregulerMouseClicked(evt);
            }
        });
        rdreguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdregulerActionPerformed(evt);
            }
        });

        kualitas.add(rdpremium);
        rdpremium.setText("Premium");
        rdpremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdpremiumActionPerformed(evt);
            }
        });

        batal.setText("Batal");
        batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout formorderpanelLayout = new javax.swing.GroupLayout(formorderpanel);
        formorderpanel.setLayout(formorderpanelLayout);
        formorderpanelLayout.setHorizontalGroup(
            formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formorderpanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formorderpanelLayout.createSequentialGroup()
                        .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblnama_order, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(lblnohp_order)))
                    .addGroup(formorderpanelLayout.createSequentialGroup()
                        .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(170, 170, 170)
                        .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formorderpanelLayout.createSequentialGroup()
                                .addComponent(rdreguler, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(rdpremium)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pilihproduk, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblalamat_order)
                            .addComponent(totalharga))))
                .addGap(30, 30, 30))
            .addGroup(formorderpanelLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formorderpanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formorderpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncheckout)
                        .addGap(275, 275, 275))))
        );
        formorderpanelLayout.setVerticalGroup(
            formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formorderpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(226, 226, 226)
                .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblnama_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblnohp_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblalamat_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pilihproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(rdreguler)
                    .addComponent(rdpremium))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(totalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formorderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncheckout)
                    .addComponent(batal))
                .addGap(32, 32, 32))
        );

        mainpanel.add(formorderpanel, "card5");

        aboutpanel.setBackground(new java.awt.Color(0, 153, 204));

        jLabel4.setText("Developed by:");

        jLabel18.setText("About");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("KELOMPOK 1");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("PayungIN.io V.1.0");

        javax.swing.GroupLayout aboutpanelLayout = new javax.swing.GroupLayout(aboutpanel);
        aboutpanel.setLayout(aboutpanelLayout);
        aboutpanelLayout.setHorizontalGroup(
            aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutpanelLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutpanelLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutpanelLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutpanelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(204, 204, 204))))
            .addGroup(aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutpanelLayout.createSequentialGroup()
                    .addGap(289, 289, 289)
                    .addComponent(jLabel18)
                    .addContainerGap(300, Short.MAX_VALUE)))
        );
        aboutpanelLayout.setVerticalGroup(
            aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutpanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel21)
                .addGap(88, 88, 88)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutpanelLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jLabel18)
                    .addContainerGap(480, Short.MAX_VALUE)))
        );

        mainpanel.add(aboutpanel, "card6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       mainpanel.removeAll();
       mainpanel.repaint();
       mainpanel.revalidate();

       mainpanel.add(formorderpanel);
       mainpanel.repaint();
       mainpanel.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnorderprodukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderprodukMouseEntered
        // TODO add your handling code here:
        btnorderproduk.setBackground(new Color(44, 62, 80));
    }//GEN-LAST:event_btnorderprodukMouseEntered

    private void btnmyorderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmyorderMouseExited
        // TODO add your handling code here:
        btnmyorder.setBackground(new Color(255, 255, 204));
    }//GEN-LAST:event_btnmyorderMouseExited

    private void btnorderprodukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderprodukMouseExited
        // TODO add your handling code here:
        btnorderproduk.setBackground(new Color(255, 255, 204));
    }//GEN-LAST:event_btnorderprodukMouseExited

    private void btnorderprodukMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderprodukMousePressed
        // TODO add your handling code here:
        btnorderproduk.setBackground(new Color(44, 62, 80));
    }//GEN-LAST:event_btnorderprodukMousePressed

    private void btnorderprodukMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderprodukMouseReleased
        // TODO add your handling code here: 
        btnorderproduk.setBackground(new Color(255, 255, 204));
    }//GEN-LAST:event_btnorderprodukMouseReleased

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void btnmyorderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmyorderMouseEntered
        // TODO add your handling code here:
        btnmyorder.setBackground(new Color(44, 62, 80));
    }//GEN-LAST:event_btnmyorderMouseEntered

    private void btnmyorderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmyorderMousePressed
        // TODO add your handling code here:
        btnmyorder.setBackground(new Color(44, 62, 80));
    }//GEN-LAST:event_btnmyorderMousePressed

    private void btnmyorderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmyorderMouseReleased
        // TODO add your handling code here:
        btnmyorder.setBackground(new Color(255, 255, 204));
    }//GEN-LAST:event_btnmyorderMouseReleased

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        // TODO add your handling code here:
        btnlogout.setBackground(new Color(44, 62, 80));
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        // TODO add your handling code here:
        btnlogout.setBackground(new Color(255, 255, 204));
    }//GEN-LAST:event_btnlogoutMouseExited

    private void btnlogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMousePressed
        // TODO add your handling code here:
        btnlogout.setBackground(new Color(44, 62, 80));
    }//GEN-LAST:event_btnlogoutMousePressed

    private void btnlogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseReleased
        // TODO add your handling code here:
        btnlogout.setBackground(new Color(255, 255, 204));
    }//GEN-LAST:event_btnlogoutMouseReleased

    private void btnorderprodukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderprodukMouseClicked
        // TODO add your handling code here:
       mainpanel.removeAll();
       mainpanel.repaint();
       mainpanel.revalidate();

       mainpanel.add(orderprodukpanel);
       mainpanel.repaint();
       mainpanel.revalidate();
    }//GEN-LAST:event_btnorderprodukMouseClicked

    private void btnmyorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmyorderMouseClicked
        // TODO add your handling code here:
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
       
        mainpanel.add(myorderpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_btnmyorderMouseClicked

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Keluar?", "PERINGATAN",dialogBtn);
        if (dialogResult == 0){
            login n = new login();
        n.setVisible(true);
        this.setVisible(false);
        this.dispose();
        }else{
        }
    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btncheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckoutActionPerformed
        String jenis = null;
        if(rdreguler.isSelected()){
            jenis = "Reguler";
        }else if(rdpremium.isSelected()){
            jenis = "Premium";
        }
        String sql = "insert into formorder values (?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, lblnama_order.getText());
            stat.setString(2, lblnohp_order.getText());
            stat.setString(3, lblalamat_order.getText());
            stat.setString(4, String.valueOf(pilihproduk.getSelectedItem()));
            stat.setString(5, jenis);
            stat.setString(6, totalharga.getText());
            
            stat.executeUpdate();
            
            kosong();
        
        }catch (SQLException e){
            
        }datatable();
        datatable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncheckoutActionPerformed

    private void btncheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncheckoutMouseClicked
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Order?", "PERINGATAN",dialogBtn);
        if (dialogResult == 0){
            terimakasih tk = new terimakasih();
        tk.setVisible(true);
        this.setVisible(false);
        }else{
        }
    }//GEN-LAST:event_btncheckoutMouseClicked

    private void totalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalhargaActionPerformed
   
        // TODO add your handling code here:
    }//GEN-LAST:event_totalhargaActionPerformed

    private void pilihprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihprodukActionPerformed
        if(pilihproduk.getSelectedItem().equals("Payung")){
            reguler = 15000;
            premium = 17000;
        }
        else if(pilihproduk.getSelectedItem().equals("Jas Hujan")){
            reguler = 20000;
            premium = 30000;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihprodukActionPerformed

    private void rdregulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdregulerActionPerformed
        if(rdreguler.isSelected()){
            totalharga.setText(String.valueOf(reguler));
        } 
    }//GEN-LAST:event_rdregulerActionPerformed

    private void rdpremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdpremiumActionPerformed
        if(rdpremium.isSelected()){
            totalharga.setText(String.valueOf(premium));
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_rdpremiumActionPerformed

    private void rdregulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdregulerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rdregulerMouseClicked

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseEntered

    private void btnaboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaboutMouseClicked
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
       
        mainpanel.add(aboutpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaboutMouseClicked

    private void btnaboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaboutMouseEntered
    btnabout.setBackground(new Color(44, 62, 80));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaboutMouseEntered

    private void btnaboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaboutMouseExited
    btnabout.setBackground(new Color(255, 255, 204));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaboutMouseExited

    private void btnaboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaboutMousePressed
    btnabout.setBackground(new Color(44, 62, 80));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaboutMousePressed

    private void btnaboutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaboutMouseReleased
        // TODO add your handling code here:
    btnabout.setBackground(new Color(255, 255, 204));
    }//GEN-LAST:event_btnaboutMouseReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batalMouseClicked
        lblnama_order.setText("");
        lblalamat_order.setText("");
        lblnohp_order.setText("");
        totalharga.setText("");
        kualitas.clearSelection();
        pilihproduk.getSelectedItem();
        // TODO add your handling code here:
    }//GEN-LAST:event_batalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mainview().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutpanel;
    private javax.swing.JButton batal;
    private javax.swing.JPanel btnabout;
    private javax.swing.JButton btncheckout;
    private javax.swing.JPanel btnlogout;
    private javax.swing.JPanel btnmyorder;
    private javax.swing.JPanel btnorderproduk;
    private javax.swing.JTable datatable;
    private javax.swing.JPanel formorderpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup kualitas;
    private javax.swing.JTextField lblalamat_order;
    private javax.swing.JTextField lblnama_order;
    private javax.swing.JTextField lblnohp_order;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel menupanel;
    private javax.swing.JPanel myorderpanel;
    private javax.swing.JLabel nama_home;
    private javax.swing.JPanel orderprodukpanel;
    private javax.swing.JComboBox<String> pilihproduk;
    private javax.swing.JRadioButton rdpremium;
    private javax.swing.JRadioButton rdreguler;
    private javax.swing.JTextField totalharga;
    // End of variables declaration//GEN-END:variables

    private String Double(double harga) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
