/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminpayungin;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Meti Hervina
 */
public class MainViewAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainViewAdmin
     */
    public MainViewAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonhome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buttonpmasuk = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonpdikirim = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonlogout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        homepanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pmasukpanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pdikirimpanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PayungIn.io");

        jPanel1.setBackground(new java.awt.Color(163, 203, 56));

        menupanel.setBackground(new java.awt.Color(196, 229, 56));
        menupanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.yellow, java.awt.Color.yellow, java.awt.Color.yellow, java.awt.Color.yellow));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/—Pngtree—umbrella icon_4422389 (3).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setMaximumSize(new java.awt.Dimension(400, 400));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 300));

        buttonhome.setBackground(new java.awt.Color(255, 195, 18));
        buttonhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonhomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonhomeMouseReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(247, 159, 31));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 98, 102));
        jLabel1.setText("Beranda");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/—Pngtree—simple home icon_6978727 (1).png"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout buttonhomeLayout = new javax.swing.GroupLayout(buttonhome);
        buttonhome.setLayout(buttonhomeLayout);
        buttonhomeLayout.setHorizontalGroup(
            buttonhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonhomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonhomeLayout.setVerticalGroup(
            buttonhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonpmasuk.setBackground(new java.awt.Color(255, 195, 18));
        buttonpmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonpmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonpmasukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonpmasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonpmasukMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonpmasukMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonpmasukMouseReleased(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(247, 159, 31));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 98, 102));
        jLabel3.setText("Pesanan Masuk");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/—Pngtree—isolated parcel box vector icon_5592575 (1).png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout buttonpmasukLayout = new javax.swing.GroupLayout(buttonpmasuk);
        buttonpmasuk.setLayout(buttonpmasukLayout);
        buttonpmasukLayout.setHorizontalGroup(
            buttonpmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpmasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonpmasukLayout.setVerticalGroup(
            buttonpmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        buttonpdikirim.setBackground(new java.awt.Color(255, 195, 18));
        buttonpdikirim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonpdikirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonpdikirimMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonpdikirimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonpdikirimMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonpdikirimMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonpdikirimMouseReleased(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(247, 159, 31));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 98, 102));
        jLabel4.setText("Pesanan Dikirim");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/—Pngtree—fast delivery order using motorcycle_8383587 (3).png"))); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout buttonpdikirimLayout = new javax.swing.GroupLayout(buttonpdikirim);
        buttonpdikirim.setLayout(buttonpdikirimLayout);
        buttonpdikirimLayout.setHorizontalGroup(
            buttonpdikirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpdikirimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        buttonpdikirimLayout.setVerticalGroup(
            buttonpdikirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpdikirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        buttonlogout.setBackground(new java.awt.Color(255, 195, 18));
        buttonlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonlogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseReleased(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(247, 159, 31));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 98, 102));
        jLabel5.setText("Logout");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/—Pngtree—vector logout icon_4267952 (1).png"))); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout buttonlogoutLayout = new javax.swing.GroupLayout(buttonlogout);
        buttonlogout.setLayout(buttonlogoutLayout);
        buttonlogoutLayout.setHorizontalGroup(
            buttonlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonlogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        buttonlogoutLayout.setVerticalGroup(
            buttonlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonlogoutLayout.createSequentialGroup()
                .addGroup(buttonlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonpdikirim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonpmasuk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(buttonlogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(buttonhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonpmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonpdikirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonlogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainpanel.setBackground(new java.awt.Color(196, 229, 56));
        mainpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.yellow, java.awt.Color.yellow, java.awt.Color.yellow, java.awt.Color.yellow));
        mainpanel.setPreferredSize(new java.awt.Dimension(494, 721));
        mainpanel.setLayout(new java.awt.CardLayout());

        homepanel.setBackground(new java.awt.Color(196, 229, 56));
        homepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.yellow, java.awt.Color.yellow, java.awt.Color.yellow, java.awt.Color.yellow));
        homepanel.setForeground(new java.awt.Color(63, 203, 56));

        jLabel10.setBackground(new java.awt.Color(0, 98, 102));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 98, 102));
        jLabel10.setText("PayungIn.io");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/—Pngtree—umbrella icon_4490468 (1)2.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 98, 102));
        jLabel12.setText("Halo, selamat datang!");

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 98, 102));
        jLabel13.setText("Yuk, segera proses pesanan :)");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/food_delivery.gif"))); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout homepanelLayout = new javax.swing.GroupLayout(homepanel);
        homepanel.setLayout(homepanelLayout);
        homepanelLayout.setHorizontalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel12))
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel13)))
                .addGap(45, 45, 45))
        );
        homepanelLayout.setVerticalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(37, 37, 37)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        mainpanel.add(homepanel, "card2");

        pmasukpanel.setBackground(new java.awt.Color(196, 229, 56));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 98, 102));
        jLabel15.setText("Pesanan Masuk");

        javax.swing.GroupLayout pmasukpanelLayout = new javax.swing.GroupLayout(pmasukpanel);
        pmasukpanel.setLayout(pmasukpanelLayout);
        pmasukpanelLayout.setHorizontalGroup(
            pmasukpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmasukpanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel15)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        pmasukpanelLayout.setVerticalGroup(
            pmasukpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmasukpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(678, Short.MAX_VALUE))
        );

        mainpanel.add(pmasukpanel, "card3");

        pdikirimpanel.setBackground(new java.awt.Color(196, 229, 56));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 98, 102));
        jLabel16.setText("Pesanan Dikirim");

        javax.swing.GroupLayout pdikirimpanelLayout = new javax.swing.GroupLayout(pdikirimpanel);
        pdikirimpanel.setLayout(pdikirimpanelLayout);
        pdikirimpanelLayout.setHorizontalGroup(
            pdikirimpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pdikirimpanelLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(151, 151, 151))
        );
        pdikirimpanelLayout.setVerticalGroup(
            pdikirimpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdikirimpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(678, Short.MAX_VALUE))
        );

        mainpanel.add(pdikirimpanel, "card4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseEntered
        // TODO add your handling code here:
        buttonhome.setBackground(new Color(247, 159, 31));
    }//GEN-LAST:event_buttonhomeMouseEntered

    private void buttonhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseExited
        // TODO add your handling code here:
        buttonhome.setBackground(new Color(255, 195, 18));
    }//GEN-LAST:event_buttonhomeMouseExited

    private void buttonhomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMousePressed
        // TODO add your handling code here:
        buttonhome.setBackground(new Color(238, 90, 36));
    }//GEN-LAST:event_buttonhomeMousePressed

    private void buttonhomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseReleased
        // TODO add your handling code here:
        buttonhome.setBackground(new Color(247, 159, 31));
    }//GEN-LAST:event_buttonhomeMouseReleased

    private void buttonpmasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpmasukMouseEntered
        // TODO add your handling code here:
        buttonpmasuk.setBackground(new Color(247, 159, 31));
    }//GEN-LAST:event_buttonpmasukMouseEntered

    private void buttonpmasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpmasukMouseExited
        // TODO add your handling code here:
        buttonpmasuk.setBackground(new Color(255, 195, 18));
    }//GEN-LAST:event_buttonpmasukMouseExited

    private void buttonpmasukMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpmasukMousePressed
        // TODO add your handling code here:
        buttonpmasuk.setBackground(new Color(238, 90, 36));
    }//GEN-LAST:event_buttonpmasukMousePressed

    private void buttonpmasukMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpmasukMouseReleased
        // TODO add your handling code here:
        buttonpmasuk.setBackground(new Color(247, 159, 31));
    }//GEN-LAST:event_buttonpmasukMouseReleased

    private void buttonpdikirimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpdikirimMouseEntered
        // TODO add your handling code here:
        buttonpdikirim.setBackground(new Color(247, 159, 31));
    }//GEN-LAST:event_buttonpdikirimMouseEntered

    private void buttonpdikirimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpdikirimMouseExited
        // TODO add your handling code here:
        buttonpdikirim.setBackground(new Color(255, 195, 18));
    }//GEN-LAST:event_buttonpdikirimMouseExited

    private void buttonpdikirimMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpdikirimMousePressed
        // TODO add your handling code here:
        buttonpdikirim.setBackground(new Color(238, 90, 36));
    }//GEN-LAST:event_buttonpdikirimMousePressed

    private void buttonpdikirimMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpdikirimMouseReleased
        // TODO add your handling code here:
        buttonpdikirim.setBackground(new Color(247, 159, 31));
    }//GEN-LAST:event_buttonpdikirimMouseReleased

    private void buttonlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseEntered
        // TODO add your handling code here:
        buttonlogout.setBackground(new Color(247, 159, 31));
    }//GEN-LAST:event_buttonlogoutMouseEntered

    private void buttonlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseExited
        // TODO add your handling code here:
        buttonlogout.setBackground(new Color(255, 195, 18));
    }//GEN-LAST:event_buttonlogoutMouseExited

    private void buttonlogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMousePressed
        // TODO add your handling code here:
        buttonlogout.setBackground(new Color(238, 90, 36));
    }//GEN-LAST:event_buttonlogoutMousePressed

    private void buttonlogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseReleased
        // TODO add your handling code here:
        buttonlogout.setBackground(new Color(247, 159, 31));
    }//GEN-LAST:event_buttonlogoutMouseReleased

    private void buttonhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseClicked
        // TODO add your handling code here:
        // remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        //add oanel
        mainpanel.add(homepanel);
        
    }//GEN-LAST:event_buttonhomeMouseClicked

    private void buttonpmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpmasukMouseClicked
        // TODO add your handling code here:
        // remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        //add oanel
        mainpanel.add(pmasukpanel);
    }//GEN-LAST:event_buttonpmasukMouseClicked

    private void buttonpdikirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpdikirimMouseClicked
        // TODO add your handling code here:
        // remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        //add oanel
        mainpanel.add(pdikirimpanel);
    }//GEN-LAST:event_buttonpdikirimMouseClicked

    private void buttonlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseClicked
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin Logout?", "PERINGATAN", dialogBtn);
        this.setVisible(false);
        if(dialogResult == 0) { 
        //kondisi
                PageUtamaAdmin n = new PageUtamaAdmin();
                n.setVisible(true);
        }else{
        
        }
    }//GEN-LAST:event_buttonlogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainViewAdmin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonhome;
    private javax.swing.JPanel buttonlogout;
    private javax.swing.JPanel buttonpdikirim;
    private javax.swing.JPanel buttonpmasuk;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel menupanel;
    private javax.swing.JPanel pdikirimpanel;
    private javax.swing.JPanel pmasukpanel;
    // End of variables declaration//GEN-END:variables
}
